[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 1000000
via_ir = true
solc_version = "0.8.19"
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]
fs_permissions = [{ access = "write", path = "./deployments" }]


[etherscan]
morph = { key = "${ETHERSCAN_API_KEY}", url = "https://explorer-holesky.morphl2.io/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options



[rpc_endpoints]
morph-testnet = "${RPC_URL}"